#############################################################################
# Makefile for building: myapp
# Generated by qmake (3.1) (Qt 6.8.3)
# Project:  myapp.pro
# Template: subdirs
# Command: C:\WorkableQT\qt683\bin\qmake.exe -o Makefile myapp.pro "CONFIG+=debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\WorkableQT\qt683\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\WorkableQT\qt683\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\WorkableQT\qt683\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-helpers \
		sub-models \
		sub-views \
		sub-controllers


sub-helpers-qmake_all:  FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && $(MAKE) -f Makefile qmake_all
sub-helpers: $(MAKEFILE) FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile
sub-helpers-make_first-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-helpers-make_first: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-helpers-all-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-helpers-all: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-helpers-clean-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-helpers-clean: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-helpers-distclean-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-helpers-distclean: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-helpers-install_subtargets-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-helpers-install_subtargets: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-helpers-uninstall_subtargets-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-helpers-uninstall_subtargets: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-models-qmake_all: sub-helpers-qmake_all FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && $(MAKE) -f Makefile qmake_all
sub-models: $(MAKEFILE) FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile
sub-models-make_first-ordered: sub-helpers-make_first-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-models-make_first: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-models-all-ordered: sub-helpers-all-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-models-all: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-models-clean-ordered: sub-helpers-clean-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-models-clean: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-models-distclean-ordered: sub-helpers-distclean-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-models-distclean: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-models-install_subtargets-ordered: sub-helpers-install_subtargets-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-models-install_subtargets: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-models-uninstall_subtargets-ordered: sub-helpers-uninstall_subtargets-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-models-uninstall_subtargets: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-views-qmake_all: sub-models-qmake_all FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && $(MAKE) -f Makefile qmake_all
sub-views: $(MAKEFILE) FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile
sub-views-make_first-ordered: sub-models-make_first-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-views-make_first: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-views-all-ordered: sub-models-all-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-views-all: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-views-clean-ordered: sub-models-clean-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-views-clean: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-views-distclean-ordered: sub-models-distclean-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-views-distclean: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-views-install_subtargets-ordered: sub-models-install_subtargets-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-views-install_subtargets: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-views-uninstall_subtargets-ordered: sub-models-uninstall_subtargets-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-views-uninstall_subtargets: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-controllers-qmake_all: sub-views-qmake_all FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && $(MAKE) -f Makefile qmake_all
sub-controllers: $(MAKEFILE) FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile
sub-controllers-make_first-ordered: sub-views-make_first-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-controllers-make_first: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile 
sub-controllers-all-ordered: sub-views-all-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-controllers-all: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile all
sub-controllers-clean-ordered: sub-views-clean-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-controllers-clean: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile clean
sub-controllers-distclean-ordered: sub-views-distclean-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-controllers-distclean: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile distclean
sub-controllers-install_subtargets-ordered: sub-views-install_subtargets-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-controllers-install_subtargets: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile install
sub-controllers-uninstall_subtargets-ordered: sub-views-uninstall_subtargets-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall
sub-controllers-uninstall_subtargets: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile uninstall

Makefile: myapp.pro ..\..\WorkableQT\qt683\mkspecs\win32-msvc\qmake.conf ..\..\WorkableQT\qt683\mkspecs\features\spec_pre.prf \
		..\..\WorkableQT\qt683\mkspecs\common\windows-desktop.conf \
		..\..\WorkableQT\qt683\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\WorkableQT\qt683\mkspecs\common\windows-vulkan.conf \
		..\..\WorkableQT\qt683\mkspecs\common\msvc-desktop.conf \
		..\..\WorkableQT\qt683\mkspecs\qconfig.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_ext_freetype.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_ext_libjpeg.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_ext_libpng.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_core.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_core_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_dbus.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_entrypoint_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_example_icons_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_freetype_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_gui.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_jpeg_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsanimation.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsanimation_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsplatform.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsplatform_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labssettings.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labssettings_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labssharedimage.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_network.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_network_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_opengl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_openglwidgets.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_png_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qml.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlassetdownloader.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlcompiler.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlcore.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlcore_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmldom_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlintegration.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlintegration_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlls_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlmeta.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlmeta_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlnetwork.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlnetwork_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quick.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2basic.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fusion.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2imagine.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2material.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2material_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2universal.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickeffects_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicklayouts.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickvectorimage.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickvectorimage_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_sql.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_testinternals_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_testlib.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_widgets.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_xml.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\WorkableQT\qt683\mkspecs\features\qt_functions.prf \
		..\..\WorkableQT\qt683\mkspecs\features\qt_config.prf \
		..\..\WorkableQT\qt683\mkspecs\win32-msvc\qmake.conf \
		..\..\WorkableQT\qt683\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\WorkableQT\qt683\mkspecs\features\exclusive_builds.prf \
		..\..\WorkableQT\qt683\mkspecs\common\msvc-version.conf \
		..\..\WorkableQT\qt683\mkspecs\features\toolchain.prf \
		..\..\WorkableQT\qt683\mkspecs\features\default_pre.prf \
		..\..\WorkableQT\qt683\mkspecs\features\win32\default_pre.prf \
		..\..\WorkableQT\qt683\mkspecs\features\resolve_config.prf \
		..\..\WorkableQT\qt683\mkspecs\features\exclusive_builds_post.prf \
		..\..\WorkableQT\qt683\mkspecs\features\default_post.prf \
		..\..\WorkableQT\qt683\mkspecs\features\precompile_header.prf \
		..\..\WorkableQT\qt683\mkspecs\features\warn_on.prf \
		..\..\WorkableQT\qt683\mkspecs\features\qmake_use.prf \
		..\..\WorkableQT\qt683\mkspecs\features\file_copies.prf \
		..\..\WorkableQT\qt683\mkspecs\features\win32\windows.prf \
		..\..\WorkableQT\qt683\mkspecs\features\testcase_targets.prf \
		..\..\WorkableQT\qt683\mkspecs\features\exceptions.prf \
		..\..\WorkableQT\qt683\mkspecs\features\yacc.prf \
		..\..\WorkableQT\qt683\mkspecs\features\lex.prf \
		myapp.pro
	$(QMAKE) -o Makefile myapp.pro "CONFIG+=debug"
..\..\WorkableQT\qt683\mkspecs\features\spec_pre.prf:
..\..\WorkableQT\qt683\mkspecs\common\windows-desktop.conf:
..\..\WorkableQT\qt683\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\WorkableQT\qt683\mkspecs\common\windows-vulkan.conf:
..\..\WorkableQT\qt683\mkspecs\common\msvc-desktop.conf:
..\..\WorkableQT\qt683\mkspecs\qconfig.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_ext_freetype.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_ext_libjpeg.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_ext_libpng.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_concurrent.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_core.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_core_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_dbus.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_entrypoint_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_example_icons_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_freetype_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_gui.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_gui_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_harfbuzz_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_jpeg_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsanimation.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsanimation_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsplatform.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsplatform_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsqmlmodels.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labssettings.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labssettings_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labssharedimage.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labssharedimage_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_network.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_network_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_opengl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_openglwidgets.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_openglwidgets_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_png_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_printsupport.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qml.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qml_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlassetdownloader.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlcompiler.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlcore.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlcore_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmldom_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlintegration.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlintegration_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmllocalstorage.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlls_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlmeta.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlmeta_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlnetwork.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlnetwork_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmltest.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quick.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quick_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2basic.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fusion.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2imagine.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2material.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2material_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2universal.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickeffects_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicklayouts.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicklayouts_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickvectorimage.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickvectorimage_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_sql.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_sql_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_testinternals_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_testlib.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_widgets.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_xml.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_xml_private.pri:
..\..\WorkableQT\qt683\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\WorkableQT\qt683\mkspecs\features\qt_functions.prf:
..\..\WorkableQT\qt683\mkspecs\features\qt_config.prf:
..\..\WorkableQT\qt683\mkspecs\win32-msvc\qmake.conf:
..\..\WorkableQT\qt683\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\WorkableQT\qt683\mkspecs\features\exclusive_builds.prf:
..\..\WorkableQT\qt683\mkspecs\common\msvc-version.conf:
..\..\WorkableQT\qt683\mkspecs\features\toolchain.prf:
..\..\WorkableQT\qt683\mkspecs\features\default_pre.prf:
..\..\WorkableQT\qt683\mkspecs\features\win32\default_pre.prf:
..\..\WorkableQT\qt683\mkspecs\features\resolve_config.prf:
..\..\WorkableQT\qt683\mkspecs\features\exclusive_builds_post.prf:
..\..\WorkableQT\qt683\mkspecs\features\default_post.prf:
..\..\WorkableQT\qt683\mkspecs\features\precompile_header.prf:
..\..\WorkableQT\qt683\mkspecs\features\warn_on.prf:
..\..\WorkableQT\qt683\mkspecs\features\qmake_use.prf:
..\..\WorkableQT\qt683\mkspecs\features\file_copies.prf:
..\..\WorkableQT\qt683\mkspecs\features\win32\windows.prf:
..\..\WorkableQT\qt683\mkspecs\features\testcase_targets.prf:
..\..\WorkableQT\qt683\mkspecs\features\exceptions.prf:
..\..\WorkableQT\qt683\mkspecs\features\yacc.prf:
..\..\WorkableQT\qt683\mkspecs\features\lex.prf:
myapp.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile myapp.pro "CONFIG+=debug"

qmake_all: sub-helpers-qmake_all sub-models-qmake_all sub-views-qmake_all sub-controllers-qmake_all FORCE

make_first: sub-helpers-make_first-ordered sub-models-make_first-ordered sub-views-make_first-ordered sub-controllers-make_first-ordered  FORCE
all: sub-helpers-all-ordered sub-models-all-ordered sub-views-all-ordered sub-controllers-all-ordered  FORCE
clean: sub-helpers-clean-ordered sub-models-clean-ordered sub-views-clean-ordered sub-controllers-clean-ordered  FORCE
distclean: sub-helpers-distclean-ordered sub-models-distclean-ordered sub-views-distclean-ordered sub-controllers-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-helpers-install_subtargets-ordered sub-models-install_subtargets-ordered sub-views-install_subtargets-ordered sub-controllers-install_subtargets-ordered FORCE
uninstall_subtargets: sub-helpers-uninstall_subtargets-ordered sub-models-uninstall_subtargets-ordered sub-views-uninstall_subtargets-ordered sub-controllers-uninstall_subtargets-ordered FORCE

sub-helpers-debug_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile debug
sub-models-debug_ordered: sub-helpers-debug_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile debug
sub-views-debug_ordered: sub-models-debug_ordered 
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile debug
sub-controllers-debug_ordered: sub-views-debug_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile debug
debug: sub-helpers-debug_ordered sub-models-debug_ordered sub-views-debug_ordered sub-controllers-debug_ordered

sub-helpers-release_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile release
sub-models-release_ordered: sub-helpers-release_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile release
sub-views-release_ordered: sub-models-release_ordered 
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile release
sub-controllers-release_ordered: sub-views-release_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile release
release: sub-helpers-release_ordered sub-models-release_ordered sub-views-release_ordered sub-controllers-release_ordered

sub-helpers-check_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile check
sub-models-check_ordered: sub-helpers-check_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile check
sub-views-check_ordered: sub-models-check_ordered 
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile check
sub-controllers-check_ordered: sub-views-check_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile check
check: sub-helpers-check_ordered sub-models-check_ordered sub-views-check_ordered sub-controllers-check_ordered

sub-helpers-benchmark_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd helpers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\helpers\helpers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile benchmark
sub-models-benchmark_ordered: sub-helpers-benchmark_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd models\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\models\models.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile benchmark
sub-views-benchmark_ordered: sub-models-benchmark_ordered 
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd views\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\views\views.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile benchmark
sub-controllers-benchmark_ordered: sub-views-benchmark_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd controllers\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\treeFrogProject\myapp\controllers\controllers.pro "CONFIG+=debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-helpers-benchmark_ordered sub-models-benchmark_ordered sub-views-benchmark_ordered sub-controllers-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

